<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.bookstore</groupId>
  <artifactId>bookstore-monolith</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>bookstore-service</module>
  </modules>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spotify.version>1.2.2</spotify.version>
    <docker.image.tag>alpine</docker.image.tag>
    <actuator.version>3.2.12</actuator.version>
    <spring-boot.version>3.2.12</spring-boot.version>
    <spring-data-commons.version>3.2.12</spring-data-commons.version>
    <spring-data-relational.version>3.2.12</spring-data-relational.version>
    <starter-bootstrap.version>4.1.2</starter-bootstrap.version>
    <config.version>4.1.1</config.version>
    <spring-boot-autoconfigure.version>3.2.12</spring-boot-autoconfigure.version>
    <spring-boot-starter-web.version>3.2.12</spring-boot-starter-web.version>
    <spring-boot-starter-security.version>3.28.18</spring-boot-starter-security.version>
    <spring-webflux.version>6.2.0</spring-webflux.version>
    <gson.version>2.10.1</gson.version>
    <jackson-core.version>2.15.4</jackson-core.version>
    <jackson-databind.version>2.15.4</jackson-databind.version>
    <liquibase.version>4.27.0</liquibase.version>
    <postgresql.version>42.7.3</postgresql.version>
    <commons-dbcp2.version>2.12.0</commons-dbcp2.version>
    <hibernate-validator.version>8.0.1.Final</hibernate-validator.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <version>${actuator.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <!-- Import dependency management from Spring Boot -->
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.2.12</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
        <version>${spring-boot-starter-web.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-war-plugin</artifactId>
          <version>3.3.2</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.0</version>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>3.1.10</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>