spring:
  cloud:
    config:
      import-check:
        enabled: false
  main:
    lazy-initialization: true
  application:
    name: bookstoreservice
  datasource:
    url: jdbc:postgresql://localhost:5831/book-store?prepareThreshold=0
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    cloud:
      service-registry:
        auto-registration:
          enabled: false
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  level:
    level:
      root: "warn"
    org:
      springframework:
        web: "debug"
      store:
        book:
          profiler:
            CustomPerformanceMonitorInterceptor: TRACE
hibernate:
  show_sql: true
  dialect: org.hibernate.dialect.PostgreSQLDialect
  batch.size: 200
  hbm2ddl.auto: update
management:
  endpoint:
    health:
      diskspace:
        enabled: true
    beans:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
